isd = 2
description = "Initial TRC for ISD 2"
serial_version = 1
base_version = 1
grace_period = "0s"
voting_quorum = 2

core_ases = [210, 211]
authoritative_ases = [210, 211]

cert_files = [
  "/home/alonso/Escritorio/scion-orchestrator/escenario/pki/ISD2/210/root/cp-root.pem",
  "/home/alonso/Escritorio/scion-orchestrator/escenario/pki/ISD2/211/root/cp-root.pem",
  "/home/alonso/Escritorio/scion-orchestrator/escenario/pki/ISD2/210/voting/regular-voting.pem",
  "/home/alonso/Escritorio/scion-orchestrator/escenario/pki/ISD2/211/voting/regular-voting.pem",
  "/home/alonso/Escritorio/scion-orchestrator/escenario/pki/ISD2/210/voting/sensitive-voting.pem",
  "/home/alonso/Escritorio/scion-orchestrator/escenario/pki/ISD2/211/voting/sensitive-voting.pem"
]

[validity]
not_before = 2026-04-13T15:08:10Z
not_after = 2027-04-13T16:08:10Z
