isd_as = "2-240"
mode   = "as"

[ca.service]
mode          = "delegating"
shared_secret = "secrets/secret-240.txt"
addr          = "http://172.20.2.10:3000"
client_id     = "240"

[metrics]
server = "0.0.0.0:33400"
