isd_as = "4-410"
mode   = "as"

[ca]
server  = "0.0.0.0:3000"
# Lista de clientes (resto de ASes del ISD) con sus respectivos secretos
clients = ["420:secrets/secret-420.txt",
           "430:secrets/secret-430.txt",
           "440:secrets/secret-440.txt",
           "450:secrets/secret-450.txt"]

[metrics]
server = "0.0.0.0:33400"

[bootstrap]
# El servidor bootstrap se activa implícitamente en el puerto 8041
