isd_as = "1-120"
mode   = "as"

[ca.service]
mode          = "delegating"
shared_secret = "secrets/secret-120.txt"
addr          = "http://172.20.1.10:3000"
client_id     = "120"

[metrics]
server = "0.0.0.0:33400"
