isd_as = "3-350"
mode   = "as"

[ca.service]
mode          = "delegating"
shared_secret = "secrets/secret-350.txt"
addr          = "http://172.20.3.10:3000"
client_id     = "350"

[metrics]
server = "0.0.0.0:33400"
