isd_as = "3-330"
mode   = "as"

[ca.service]
mode          = "delegating"
shared_secret = "secrets/secret-330.txt"
addr          = "http://172.20.3.10:3000"
client_id     = "330"

[metrics]
server = "0.0.0.0:33400"
