isd_as = "4-450"
mode   = "as"

[ca.service]
mode          = "delegating"
shared_secret = "secrets/secret-450.txt"
addr          = "http://172.20.4.10:3000"
client_id     = "450"

[metrics]
server = "0.0.0.0:33400"
